### ISSUE TITLE
Fix installation of older node versions

### ISSUE THREAD

**Issue by mortenscheel** [mortenscheel/docker-laravel#6]

**Comment by mortenscheel** [comment]
Or maybe just add a separate node container. Has to be configured to work with vite and mix.

**Comment by mortenscheel** [comment]
POC node container:

docker-compose.yml
```
node:
        container_name: tmpp_node
        restart: unless-stopped
        build:
            args:
                NODE_VERSION: 16
                VITE_PORT: ${VITE_PORT:-5173}
            context: ./docker/node
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - './:/home/node/app'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        networks:
            - app-network
```
Dockerfile
```
ARG NODE_VERSION=20
FROM node:${NODE_VERSION}

ARG VITE_PORT 5173
WORKDIR /home/node/app
EXPOSE $VITE_PORT

CMD [ "tail", "-f", "/dev/null"  ]
```
vite.config.js
```
    server: {
        host: '0.0.0.0',
        hmr: {
            host: 'localhost'
        },
    },
```
